### ISSUE TITLE
Queries don't work anymore

### ISSUE THREAD

**Issue by chovyy** [adamml/seadatanet-sparql-queries#3]
Most of the queries don't work anymore. It seems that the EDMO and EDMERP data models have changed.
@adamml: Do you know something about that or do you have any clue how to fix the queries? Currently, I'm stuck and all our update scripts stopped to work.

**Comment by adamml** [comment]
@chovyy I was not aware that these had changed - I'll take a look and see what I can do

**Comment by adamml** [comment]
@chovyy Would you be able to test the EDMO queries now please?

**Comment by chovyy** [comment]
Looks quite good. :-)

**Comment by adamml** [comment]
And can you check the EDMERPs too please?

**Comment by chovyy** [comment]
`getEDMERPUrlNameDate.rq` and `getEDMERPUrlNameAcronymDate.rq` worked after removing the `FILTER` line. I don't think that this filter is necessary anyway.

**Comment by adamml** [comment]
Thanks - I'll close this issue now then

**Comment by chovyy** [comment]
Thanks a lot, @adamml. Great work! :-)
